---
title: "Probability In-Class Test"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

#### Load libraries
```{r}
library(ggplot2) # plotting library
library(dplyr)   # data wrangling library
```

```{r}
# Generate a 52-card deck
suits = c('H', 'D', 'S', 'C')
cards = c(2:10, 'J', 'Q', 'K', 'A')
s = paste0(rep(cards, length(suits)), rep(suits, each = length(cards)))
```

```{r}
# Simulate dealing 5 cards to 8 hands (40 cards)
nsimulations = 1e5
simulatedData = replicate(nsimulations, sample(s, size = 40, prob = rep(1/length(s), length(s))))
```

```{r}
# Check event that exactly 3 aces are dealt
checkEvent1 = function(data){
  return(sum(grepl('A', data)) == 3)
}
```

```{r}
# Check event that 4 hands have exactly one ace each
checkEvent2 = function(data){
  condition1 = (sum(grepl('A', data)) == 4)
  condition2 = (length(unique(ceiling(which(grepl('A', data))/ 5))) == 4)
  return(condition1 & condition2)
}
```

```{r}
# Check event that one hand has all four aces
checkEvent3 = function(data){
  condition1 = (sum(grepl('A', data)) == 4)
  condition2 = (length(unique(ceiling(which(grepl('A', data)) / 5))) == 1)
  return(condition1 & condition2)
}
```

```{r}
# Check event given that the ace of spades was among the cards dealt, that it is in a hand with at least one other spade.
checkEvent4 = function(data){
  hand = ceiling(which(data == 'AS') / 5)
  return('AH' %in% data[c((1+(hand-1)*5):(hand*5))] | 'AD' %in% data[c((1+(hand-1)*5):(hand*5))] | 'AC' %in% data[c((1+(hand-1)*5):(hand*5))])
  }
```

```{r}
# Check event given that exactly two aces and two queens were dealt, that both aces are together in one hand and both queens are together in a different hand.
checkEvent5 = function(data){
  condition1 = (length(unique(ceiling(which(grepl('A', data)) /5))) == 1)
  condition2 = (length(unique(ceiling(which(grepl('Q', data)) /5))) == 1)
  condition3 = (ceiling(which(grepl('A', data)) /5)) != (ceiling(which(grepl('Q', data)) /5))
  return(condition1 & condition2 & condition3)
  }
```

```{r}
# Check event given that exactly two aces and two queens were dealt with the two aces together in a hand and the two queens together in a hand that all four of those cards are together in the same hand.
checkEvent6 = function(data){
  return(unique(ceiling(which(grepl('A', data)) /5)) == unique(ceiling(which(grepl('Q', data)) /5))) 
  }
```

```{r}
# Calculate probability that exactly 3 aces are dealt
mean(apply(simulatedData, 2, checkEvent1))
```

```{r}
# Calculate probability that 4 hands have exactly one ace each
mean(apply(simulatedData, 2, checkEvent2))
```

```{r}
# Calculate probability that one hand has all four aces
mean(apply(simulatedData, 2, checkEvent3))
```

```{r}
# Calculate probability given that the ace of spades was among the cards dealt, that it is in a hand with at least one other spade.
simulatedData_reduced = simulatedData[, apply(simulatedData, 2, function(data){return('AS' %in% data)})]
mean(apply(simulatedData_reduced, 2, checkEvent4))
```

```{r}
# Calculate probability given that exactly two aces and two queens were dealt, find the probability that both aces are together in one hand and both queens are together in a different hand.
simulatedData_reduced = simulatedData[, apply(simulatedData, 2, function(data){return((sum(grepl('A', data)) == 2) & sum(grepl('Q', data)) == 2)})]
mean(apply(simulatedData_reduced, 2, checkEvent5))
```

```{r}
# Calculate probability given that exactly two aces and two queens were dealt with the two aces together in a hand and the two queens together in a hand, find the probability that all four of those cards are together in the same hand.
simulatedData_reduced = simulatedData[, apply(simulatedData, 2, function(data){return((sum(grepl('A', data)) == 2) & sum(grepl('Q', data)) == 2 & length(unique(ceiling(which(grepl('A', data)) /5))) == 1 & length(unique(ceiling(which(grepl('Q', data)) /5))) == 1)})]
mean(apply(simulatedData_reduced, 2, checkEvent6))
```

```{r}
n_success = 4
n_failure = 48
n = 40
j = 3
dhyper(j, n_success, n_failure, n)
choose(4, 3)*choose(48, 37)/choose(52, 40)

sum(dhyper(c(1:4), n_success, n_failure, n))
1-phyper(0, n_success, n_failure, n)

nsimulations = 10
rhyper(nsimulations, n_success, n_failure, n)
```

```{r}
r = 20
p = 0.2
j = c(20:200)
dnbinom(j-r, r, p)
```

```{r}
j = c(20:200)
df = as.data.frame(cbind(j, dnbinom(j-r, r, p)))

# Add names to the columns
colnames(df) = c('Valuesofj', 'Probability')

p1 = ggplot(data = df) + geom_col(aes(x = Valuesofj, y = Probability), fill = 'steelblue')
p1
```

```{r}
r = 10
p = 1/6
j = c(10:50)
dnbinom(j-r, r, p)

df = as.data.frame(cbind(j, dnbinom(j-r, r, p)))

# Add names to the columns
colnames(df) = c('Valuesofj', 'Probability')

p1 = ggplot(data = df) + geom_col(aes(x = Valuesofj, y = Probability), fill = 'steelblue')
p1
which.max(dnbinom(j-r, r, p))
mean(dnbinom(10, r, p))
```

```{r}
r = 1
p = 7/8
j = c(1:20)

dnbinom(j-r, r, p)

df = as.data.frame(cbind(j, dnbinom(j-r, r, p)))

# Add names to the columns
colnames(df) = c('Valuesofj', 'Probability')

p1 = ggplot(data = df) + geom_col(aes(x = Valuesofj, y = Probability), fill = 'steelblue')
p1
which.max(dnbinom(j-r, r, p))
mean(dnbinom(1, r, p))
```